/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from 'next/server';
import { createClient } from '@sanity/client';
import { Resend } from 'resend';

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || "kcvm5a8w";
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || "production";
const token = process.env.SANITY_API_TOKEN;

const client = createClient({
  projectId,
  dataset,
  token,
  useCdn: false,
  apiVersion: '2024-03-19',
});

// Initialize Resend with your API key
const resend = new Resend(process.env.RESEND_API_KEY || "re_dummykey123456789");

export async function POST(request: Request) {
  try {
    const data = await request.json();
    
    // 1. Create a new document in the Sanity dataset
    let sanityId = null;
    try {
      const result = await client.create({
        _type: 'contact',
        firstName: data.firstName,
        lastName: data.lastName,
        email: data.email,
        phone: data.phone || '',
        subject: data.subject,
        message: data.message,
        status: 'new',
        submittedAt: new Date().toISOString()
      });
      sanityId = result._id;
    } catch (sanityError) {
      console.error('Failed to log inquiry in Sanity:', sanityError);
      // We continue to try sending the email even if Sanity fails
    }

    // 2. Send an email notification to the gallery via Resend
    try {
      await resend.emails.send({
        from: 'Arthur James Galleries <inquiries@arthurjamesgallery.com>', // MUST be a verified domain in Resend
        to: ['privatesales@arthurjamesadvisory.com'],
        subject: `New Inquiry: ${data.subject} from ${data.firstName} ${data.lastName}`,
        html: `
          <div style="font-family: sans-serif; max-w-xl; margin: 0 auto; padding: 20px; background: #F9F6F0; color: #002244;">
            <h2 style="font-family: serif; font-size: 24px; margin-bottom: 20px; border-bottom: 1px solid #002244; padding-bottom: 10px;">New Gallery Inquiry</h2>
            <p><strong>Name:</strong> ${data.firstName} ${data.lastName}</p>
            <p><strong>Email:</strong> <a href="mailto:${data.email}" style="color: #C5A059;">${data.email}</a></p>
            <p><strong>Phone:</strong> ${data.phone || 'Not provided'}</p>
            <p><strong>Subject:</strong> ${data.subject}</p>
            <div style="margin-top: 30px; padding: 20px; background: white; border: 1px solid rgba(0,34,68,0.1);">
              <p style="margin: 0; white-space: pre-wrap;">${data.message}</p>
            </div>
            <p style="margin-top: 40px; font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em; color: #666;">This message was automatically generated by the Arthur James Galleries platform.</p>
          </div>
        `
      });
    } catch (emailError) {
      console.error('Failed to send email via Resend:', emailError);
      // If there's an API key error but Sanity succeeded, we still return success to the user
      if (!sanityId) {
        throw new Error('Both database logging and email notification failed.');
      }
    }

    return NextResponse.json({ success: true, id: sanityId });
  } catch (error: any) {
    console.error('Contact form error:', error);
    return NextResponse.json({ success: false, message: error.message }, { status: 500 });
  }
}
