/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from 'next/server';
import { createClient } from '@sanity/client';
import { Resend } from 'resend';
import { env, validateEnv } from '@/lib/env';
import { isRateLimited } from '@/lib/rate-limit';

export async function POST(request: Request) {
  try {
    // 0. Rate Limiting (Prevent Spam)
    // Limits to 3 enquiries per hour per IP
    const ip = request.headers.get('x-forwarded-for') || 'anonymous';
    if (isRateLimited(ip, { limit: 3, windowMs: 3600000 })) {
      return NextResponse.json(
        { success: false, message: 'Too many enquiries. Please wait an hour before trying again.' },
        { status: 429 }
      );
    }

    // 1. Validate Environment before proceeding
    validateEnv();

    const data = await request.json();
    
    // 1. Create a new document in the Sanity dataset
    const client = createClient({
      projectId: env.sanity.projectId,
      dataset: env.sanity.dataset,
      token: env.sanity.token,
      useCdn: false,
      apiVersion: '2024-03-19',
    });

    let sanityId = null;
    try {
      const result = await client.create({
        _type: 'contact',
        firstName: data.firstName,
        lastName: data.lastName,
        email: data.email,
        phone: data.phone || '',
        subject: data.subject,
        message: data.message,
        status: 'new',
        submittedAt: new Date().toISOString()
      });
      sanityId = result._id;
    } catch (sanityError) {
      console.error('Failed to log enquiry in Sanity:', sanityError);
      // We continue to try sending the email even if Sanity fails
    }

    // 2. Send an email notification to the gallery via Resend
    const resend = new Resend(env.resend.apiKey);
    try {
      // NOTE: Using onboarding@resend.dev because arthurjamesgallery.com might not be verified yet.
      // Once verified, change back to: enquiries@arthurjamesgallery.com
      const emailResult = await resend.emails.send({
        from: 'Arthur James Galleries <onboarding@resend.dev>', 
        to: ['info@arthurjamesgallery.com'],
        subject: `New Enquiry: ${data.subject} from ${data.firstName} ${data.lastName}`,
        html: `
          <div style="font-family: sans-serif; max-w-xl; margin: 0 auto; padding: 20px; background: #F9F6F0; color: #002244;">
            <h2 style="font-family: serif; font-size: 24px; margin-bottom: 20px; border-bottom: 1px solid #002244; padding-bottom: 10px;">New Gallery Enquiry</h2>
            <p><strong>Name:</strong> ${data.firstName} ${data.lastName}</p>
            <p><strong>Email:</strong> <a href="mailto:${data.email}" style="color: #C5A059;">${data.email}</a></p>
            <p><strong>Phone:</strong> ${data.phone || 'Not provided'}</p>
            <p><strong>Subject:</strong> ${data.subject}</p>
            <div style="margin-top: 30px; padding: 20px; background: white; border: 1px solid rgba(0,34,68,0.1);">
              <p style="margin: 0; white-space: pre-wrap;">${data.message}</p>
            </div>
            <p style="margin-top: 40px; font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em; color: #666;">This message was automatically generated by the Arthur James Galleries platform.</p>
          </div>
        `
      });

      if (emailResult.error) {
        console.error('Resend API Error details:', emailResult.error);
        throw new Error(emailResult.error.message);
      }
    } catch (emailError: any) {
      console.error('Detailed Email Error:', emailError);
      // If Sanity also failed, we must throw
      if (!sanityId) {
        throw new Error(`Submission failed: ${emailError.message}`);
      }
    }

    return NextResponse.json({ success: true, id: sanityId });
  } catch (error: any) {
    console.error('Contact form error:', error);
    return NextResponse.json({ success: false, message: error.message }, { status: 500 });
  }
}
