import { defineField, defineType } from "sanity";

export const artwork = defineType({
  name: "artwork",
  title: "Artwork",
  type: "document",
  groups: [
    { name: "details", title: "General Details" },
    { name: "physical", title: "Physical Attributes" },
    { name: "acquisition", title: "Acquisition & Status" },
  ],
  fields: [
    defineField({
      name: "lotNumber",
      title: "Lot / Inventory Number",
      type: "string",
      group: "details",
      description: "A unique identifier for this artwork (e.g., AJ-001 or GG-001).",
    }),
    defineField({
      name: "source",
      title: "Import Source",
      type: "string",
      group: "details",
      options: {
        list: [
          { title: "Arthur James Import", value: "arthur-james" },
          { title: "Galerie Gleis (Scrape)", value: "galerie-gleis" },
        ],
      },
      initialValue: "arthur-james",
    }),
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "details",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "details",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "artist",
      title: "Artist",
      type: "reference",
      group: "details",
      to: [{ type: "artist" }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "images",
      title: "Images",
      type: "array",
      group: "details",
      of: [{ type: "image", options: { hotspot: true } }],
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "string",
      group: "physical",
    }),
    defineField({
      name: "medium",
      title: "Medium",
      type: "string",
      group: "physical",
    }),
    defineField({
      name: "dimensions",
      title: "Dimensions",
      type: "string",
      group: "physical",
    }),
    defineField({
      name: "provenance",
      title: "Provenance",
      type: "array",
      group: "physical",
      of: [{ type: "block" }],
    }),
    defineField({
      name: "price",
      title: "Internal Price",
      type: "string",
      group: "acquisition",
      description: "For internal records only. Not displayed on the website.",
    }),
    defineField({
      name: "estimate",
      title: "Estimate",
      type: "string",
      group: "acquisition",
      description: "e.g. 'USD 150,000 - 200,000' or 'Price Upon Request'",
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      group: "acquisition",
      options: {
        list: [
          { title: "Available", value: "Available" },
          { title: "Reserved", value: "Reserved" },
          { title: "Sold", value: "Sold" },
          { title: "Private", value: "Private" },
        ],
      },
      initialValue: "Available",
    }),
    defineField({
      name: "featured",
      title: "Featured Artwork",
      type: "boolean",
      initialValue: false,
      group: "acquisition",
    }),
  ],
});
